# Generated by Django 4.0.2 on 2022-08-15 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_remove_kitchen_address_remove_kitchen_image_and_more'),
        ('administrator', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantservice',
            name='kitchens',
        ),
        migrations.AddField(
            model_name='restaurantservice',
            name='kitchen',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant', to='kitchen.kitchen'),
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
