# Generated by Django 4.0.2 on 2022-08-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_remove_restaurantservice_kitchens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
    ]
