# Generated by Django 4.0.2 on 2022-08-17 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0008_delete_news_remove_order_payment_delete_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0004_remove_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantservice',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurantservice',
            name='kitchen',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_kitchen', to='kitchen.kitchen'),
        ),
    ]
