# Generated by Django 4.0.2 on 2022-08-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_alter_restaurantservice_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=25)),
                ('text', models.TextField()),
                ('attached_file', models.FileField(upload_to='message/files/')),
            ],
        ),
    ]
