# Generated by Django 4.0.2 on 2022-08-18 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attached_file',
            field=models.ImageField(upload_to='message/files/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 19, 57, 14, 996150)),
        ),
    ]
