# Generated by Django 4.0.2 on 2022-09-01 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_restaurantservice_foodify_chat_and_more'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerchat',
            name='attendant',
        ),
        migrations.AddField(
            model_name='customerchat',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_chats', to='administrator.restaurantservice'),
        ),
    ]
