# Generated by Django 3.2.1 on 2022-08-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_remove_kitchen_attendant_kitchen_attendants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered',
            name='delivered',
        ),
        migrations.AddField(
            model_name='ordered',
            name='status',
            field=models.CharField(choices=[('D', 'Delivered'), ('R', 'Decline'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
