# Generated by Django 4.0.2 on 2022-08-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_ordered_delivered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
