# Generated by Django 3.2.1 on 2022-08-25 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0010_auto_20220825_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.kitchen'),
        ),
    ]
