# Generated by Django 3.2.1 on 2022-08-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0010_orderfeed'),
        ('kitchen', '0011_ordered_kitchen'),
    ]

    operations = [
    ]
