# Generated by Django 4.0.2 on 2022-08-26 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitchen', '0012_merge_0010_orderfeed_0011_ordered_kitchen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered',
            name='delivery_point',
        ),
        migrations.RemoveField(
            model_name='ordered',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_point',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('D', 'Pay on delivery'), ('N', 'Not specify'), ('O', 'Pay online')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_no',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('D', 'Delivered'), ('R', 'Decline'), ('P', 'Pending')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
