# Generated by Django 4.0.2 on 2022-08-26 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0014_alter_order_customer_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kitchen.payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('W', 'Waiting for order'), ('N', 'Not completed'), ('C', 'Completed')], default='N', max_length=1),
        ),
    ]
