# Generated by Django 4.0.2 on 2022-08-27 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0015_remove_ordered_payment_order_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='kitchen_offered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='kitchen.kitchen'),
        ),
        migrations.AlterField(
            model_name='ordered',
            name='kitchen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.kitchen'),
        ),
    ]
